# Generated by Django 3.1.1 on 2020-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120)),
                ('inverter_name', models.CharField(max_length=120)),
                ('alarm', models.CharField(max_length=120)),
                ('occurance_time', models.CharField(max_length=120)),
                ('clearance_time', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UnClearedLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120)),
                ('inverter_name', models.CharField(max_length=120)),
                ('alarm', models.CharField(max_length=120)),
                ('occurance_time', models.CharField(max_length=120)),
                ('clearance_time', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
